### ISSUE TITLE
icarus crash on docker for windows - unhandled page fault expection

### ISSUE THREAD

**Issue by Steveiwonder** [mornedhels/icarus-server#46]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Used image version

latest

### Used docker compose file or docker command

```
  icarus:
    image: mornedhels/icarus-server:latest
    container_name: icarus
    hostname: icarus
    restart: unless-stopped
    stop_grace_period: 90s
    ports:
      - "17777:17777/udp"
      - "27015:27015/udp"
    volumes:
      - C:/docker/icarus/data:/home/icarus/drive_c/icarus
      - C:/docker/icarus/game:/opt/icarus
    environment:
      - SERVER_NAME=xxxx
      - SERVER_PASSWORD=xxxxx
      - SERVER_ADMIN_PASSWORD=xxxx
      - SERVER_PORT=17777
      - SERVER_QUERYPORT=27015
      - PUID=4711
      - PGID=4711


```

### What you expected to see, versus what you actually saw

Expected server to launch

### Logs from the container

2023-12-01 12:10:32 Dec  1 12:10:32 icarus supervisord: icarus-server 023c:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
2023-12-01 12:10:32 Dec  1 12:10:32 icarus supervisord: icarus-server 023c:err:winediag:nodrv_CreateWindow L"Make sure that your X server is running and that $DISPLAY is set correctly."
2023-12-01 12:10:32 2023-12-01 12:10:32,796 INFO reaped unknown pid 473 (exit status 1)
2023-12-01 12:10:32 Dec  1 12:10:32 icarus supervisord: icarus-server 0234:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
2023-12-01 12:10:32 Dec  1 12:10:32 icarus supervisord: icarus-server 0234:err:winediag:nodrv_CreateWindow L"Make sure that your X server is running and that $DISPLAY is set correctly."
2023-12-01 12:10:33 2023-12-01 12:10:33,797 INFO reaped unknown pid 460 (exit status 0)
2023-12-01 12:10:42 2023-12-01 12:10:42,807 INFO success: icarus-server entered RUNNING state, process has stayed up for > than 10 seconds (startsecs)
2023-12-01 12:11:16 Dec  1 12:11:16 icarus supervisord: icarus-server INFO - Releasing PID file /var/run/icarus/icarus-server.pid
2023-12-01 12:11:16 2023-12-01 12:11:16,654 INFO exited: icarus-server (exit status 0; expected)
2023-12-01 12:11:16 Dec  1 12:11:16 icarus supervisord: icarus-server INFO - Shutdown complete
2023-12-01 12:11:16 2023-12-01 12:11:16,655 INFO spawned: 'icarus-server' with pid 476
2023-12-01 12:11:16 Dec  1 12:11:16 icarus supervisord: icarus-server INFO - Running icarus-server
2023-12-01 12:11:16 Dec  1 12:11:16 icarus supervisord: icarus-server wine: Unhandled page fault on execute access to 000000014446A000 at address 000000014446A000 (thread 0248), starting debugger...
2023-12-01 12:11:16 Dec  1 12:11:16 icarus supervisord: icarus-server 0258:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
2023-12-01 12:11:16 Dec  1 12:11:16 icarus supervisord: icarus-server 0258:err:winediag:nodrv_CreateWindow L"Make sure that your X server is running and that $DISPLAY is set correctly."
2023-12-01 12:11:16 2023-12-01 12:11:16,810 INFO reaped unknown pid 484 (exit status 1)
2023-12-01 12:11:16 Dec  1 12:11:16 icarus supervisord: icarus-server 0250:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
2023-12-01 12:11:16 Dec  1 12:11:16 icarus supervisord: icarus-server 0250:err:winediag:nodrv_CreateWindow L"Make sure that your X server is running and that $DISPLAY is set correctly."
2023-12-01 12:11:17 2023-12-01 12:11:17,813 INFO reaped unknown pid 471 (exit status 0)
2023-12-01 12:11:26 2023-12-01 12:11:26,823 INFO success: icarus-server entered RUNNING state, process has stayed up for > than 10 seconds (startsecs)
