### ISSUE TITLE
Disable auto-update via env variable

### ISSUE THREAD

**Issue by DrParanoia** [mornedhels/icarus-server#76]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Feature description

Hi! Thanks for the image, works great!

Could you please add an env variable like `AUTO_UPDATE=false` or something? 😄 Some of my friends have a really slow connection, and yesterday we needed to restart the server, which caused the server to update. But it takes A LOT of time to update the game for some of my buddies, so I would rather update manually at a better time.

Thanks!

**Comment by cp-fabian-pittroff** [comment]
Hey @DrParanoia, thanks for the idea. I'll add it and report back.

**Comment by DrParanoia** [comment]
Thanks a bunch! @cp-fabian-pittroff

**Comment by cp-fabian-pittroff** [comment]
Environment variable is `UPDATE_SKIP`. Docker image should be available shortly. You can try it out with the `dev`-tag.

**Comment by DrParanoia** [comment]
> Environment variable is `UPDATE_SKIP`. Docker image should be available shortly. You can try it out with the `dev`-tag.

Cool! That was fast! Will try when the game updates this week 😄

**Comment by DrParanoia** [comment]
Updated to @dev, let's see if it auto-updates when the update releases 😃

**Comment by DrParanoia** [comment]
Nope 😢 Still updates after a restart... my docker-compose file is
```
version: "3"
services:
  icarus:
    image: mornedhels/icarus-server:dev
    container_name: icarus
    hostname: icarus
    restart: unless-stopped
    stop_grace_period: 90s
    ports:
      - "17777:17777/udp"
      - "27015:27015/udp"
    volumes:
      - ./data:/home/icarus/drive_c/icarus
      - ./game:/opt/icarus
    environment:
      - SERVER_NAME=The Vault Server
      - SERVER_ADMIN_PASSWORD=<redacted>
      - SERVER_PASSWORD=
      - SERVER_PORT=17777
      - SERVER_QUERYPORT=27015
      - SERVER_RESUME_PROSPECT=false
      - UPDATE_SKIP=true
      - PUID=4711
      - PGID=4711
```
